---
title: "final1343_final"
author: "em"
date: '2022-05-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rtweet)
library(ranger)
library(keras)
library(reticulate)
library(tensorflow) 
library(text)
library(reticulate)
library(glmnet)
library(parsnip)
library(workflows)
library(lubridate)


token <- create_token(
  app = "Em_McGlone_app",
  consumer_key = "cvCws6VHnW64OWY0oEtWig0Hh",
  consumer_secret = "97gUtYedsIFZa1joHm5LLf0QZ3YzMo4M0qt59oJzcJjsTZtJC1",
  access_token = "1490055956667023368-riJ4mkVKxZUV54OKMkPlZFXzE7cvrc",
  access_secret = "FMQMm4qxzTPJWHoYRXpI9cqOsOlJpB5P5CZDJ1hwu4fL1",
  set_renv = TRUE
)


logfit <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/logitfit_1343.rds")
svmfit <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/svmfit_1343.rds")
sui_twit2 <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/sui_twit2.rds")
test_results <- logfit <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/test_results_1343.rds")
test_sui <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/test_sui.rds")
train_input <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/train_input_1343.rds")
wordembeddings1_train <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/botocracy/1343finalhelpers/wordembeddings1_train.rds")


```

```{r}
reason0 <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/reason0_final.rds")
reason1 <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/reason1_final.rds")
reason2 <- read_rds("/Users/emdmcglone/Desktop/Spring 2022/botocracy/reason2_final.rds")

```

```{r}
sum(reason0$.pred_1)
sum(reason1$.pred_1)
sum(reason2$.pred_1)

rf_we

```